import { Inter } from 'next/font/google'
import Link from 'next/link';
import Navbar from './navbar';
// import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GraphQL React Example',
  description: 'GraphQL React Example. Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
